version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: nestjs-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nestjs_app
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: nestjs_user
      MYSQL_PASSWORD: nestjs_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=nestjs_user
      - DATABASE_PASSWORD=nestjs_password
      - DATABASE_NAME=nestjs_app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge